# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: audioreflex - Claudia Bosse - witnessing of the trees
email: email@example.com
description: > # this means to ignore newlines until "baseurl:"
  audioguia
baseurl: "/witnessingofthetrees" # the subpath of your site, e.g. /blog
audio_path: "/audio/"
episode_hero_path: "/assets/img/stops/"
url: "https://github.com/audioreflex/witnessingofthetrees" # the base hostname & protocol for your site
logo: "/assets/img/logo/logo_audioreflex.png"
twitter_username: goethesaopaulo
github_username:  audioreflex
menu_heading: "Selecione outro áudio"
index_page_text: "Escolha um áudio"
count_stops: 7
headphones_icon_color: "/assets/img/icons/headphones-dark.png"
headphones_icon_light: "/assets/img/icons/headphones-light.png"

# Build settings
markdown: kramdown

# Version settings (version number below is used for cache busting CSS and JS)
version_number: 1.0.0.1
